config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/create'
  get 'bookmarks/destroy'
   devise_for :admins, controllers: {sessions: 'admins/sessions'}

    devise_for :users
  resources :admin_users, only: [:index, :show, :edit, :update]
    get 'users/:id/mypage' => 'users#mypage', as: 'mypage_user'
  get 'users/leave' => 'users#leave'
  resources :users, only: [:edit, :update, :show]do

  member do
    get "leave"
    patch "withdrawl"
    get "bookmark"
  end
end

  get 'cat_images/all' => 'cat_images#all'
  get 'cat_images/rank' => 'cat_images#rank'
  resources :cat_images do
  	resource :favorites, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    end

  get 'homes/about'
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :cat_image
end

app/models/cat_image.rb
class CatImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :users, through: :bookmarks

	validates :image, presence: true
	validates :catname, presence: true
	validates :memo, presence: true




	acts_as_taggable

	def favorited_by?(user)
	 favorites.where(user_id: user.id).exists?
	end

	def bookmark_by?(user)
		bookmarks.where(user_id: user.id).exists?
	end
end

app/models/catimage.rb
class CatImage < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :cat_image

	validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :cat_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         # , :validatable

         validates :name, presence: true
         validates :email, presence: true
         # validates :password, presence: true


  has_many :cat_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_cat_images, through: :bookmarks, source: :cat_image

  enum status: {
  	会員: 0,
  	退会済: 1
  }





   def active_for_authentication?
  		super && (self.status === "会員")
  end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
	 before_action :authenticate_admin!
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

   def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to admin_user_path(@user)
    end
private
    def user_params
    	params.require(:user).permit(:status, :member, :unmember)
    end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
  	@cat_image = CatImage.find(params[:cat_image_id])
  	bookmark = current_user.bookmarks.new(cat_image_id: @cat_image.id)
  	bookmark.save!
  end

  def destroy
  	@cat_image = CatImage.find(params[:cat_image_id])
  	bookmark = current_user.bookmarks.find_by(cat_image_id: @cat_image.id)
  	bookmark.destroy!
  end

  def show
  	@user = User.find(params[:user_id])
    @bookmarks = Bookmark.where("user_id = ?", @user)
  end

end

app/controllers/cat_images_controller.rb
class CatImagesController < ApplicationController

before_action :authenticate_user!,except: [:index, :show, :all, :rank]


  def index
    @cat_images = CatImage.where(created_at: Time.now.all_month).page(params[:page]).reverse_order

    if params[:tag_name]
      @cat_images = CatImage.tagged_with("#{params[:tag_name]}").page(params[:page]).reverse_order
    end

    @tags = ActsAsTaggableOn::Tag.all

end

  def show
    @cat_image = CatImage.find(params[:id])
    @comment = Comment.new
  end

  def new
    @cat_image = CatImage.new
  end

  def create
    @cat_image = CatImage.new(cat_image_params)
    @cat_image.user_id = current_user.id
    if @cat_image.save
    redirect_to cat_images_path, notice:"投稿できたにゃ"
  else
    render 'new'
  end
  end

  def edit
    @cat_image = CatImage.find(params[:id])
  end

  def update
    cat_image = CatImage.find(params[:id])
    cat_image.update(cat_image_params)
      redirect_to cat_image_path(cat_image)

  end

  def destroy
    @cat_image = CatImage.find(params[:id])
    @cat_image.destroy
    redirect_to cat_images_path
  end

  def all
    @cat_images = CatImage.page(params[:page])
    @tags = ActsAsTaggableOn::Tag.all
  end

  def rank
    @all_ranks = CatImage.find(Favorite.group(:Cat_image_id).order('count(cat_image_id) desc').limit(10).pluck(:cat_image_id))
  end

  def bookmarks
    @cat_images = current_user.bookmark_cat_images.includes(:user).recent
  end

private
  def cat_image_params
    params.require(:cat_image).permit(:catname, :image, :memo, :tag_list)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
	cat_image = CatImage.find(params[:cat_image_id])
	message = current_user.comments.new(comment_params)
	message.cat_image_id = cat_image.id
	message.save
	redirect_to cat_image_path(cat_image)
	end

	def destroy
	Comment.find_by(id: params[:id], cat_image_id: params[:cat_image_id]).destroy
	redirect_to cat_image_path(params[:cat_image_id])
	end


	private
	def comment_params
		params.require(:comment).permit(:message)
	end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!

	def create
		@cat_image = CatImage.find(params[:cat_image_id])
		favorite = current_user.favorites.new(cat_image_id: @cat_image.id)
		favorite.save
	end

	def destroy
    	@cat_image = CatImage.find(params[:cat_image_id])
    	favorite = current_user.favorites.find_by(cat_image_id: @cat_image.id)
    	favorite.destroy
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :signed_in?, only: [:edit, :update]



  # def mypage
  #   user = current_user
  #   @cat_images = user.cat_images.all
  #   @user = User.find(params[:id])
  #   @cat_image = @user.cat_images.all
  #   @bookmarks = Bookmark.where("user_id = ?", @user)
  # end

  def show
    @user = User.find_by(id: params[:id])
    @cat_images = @user.cat_images
  end

  def edit
    @user = User.find(params[:id])
    if  @user == current_user
       render 'edit'
     else
      redirect_to cat_images_path
     end
  end

  def update
    @user = User.find(params[:id])
  if
    @user.update(user_params)
    redirect_to user_path(@user.id)
  else
    render 'edit'
  end
end

  def leave
    @user = User.find(params[:id])
  end

  def withdrawl
    @user = User.find(current_user.id)
    @user.update(status:"退会済")
    reset_session
    redirect_to root_path
  end

  def bookmark
    @user = User.find(params[:id])
    @bookmarks = Bookmark.where("user_id = ?", @user)
  end



  private
  def user_params
    params.require(:user).permit(:name, :email, :status, :id)
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/cat_images_helper.rb
module CatImagesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/bookmark.html.erb
お気に入り一覧
  <% @user.cat_images.each do |cat_image| %>
            <%= cat_image.user.name %>
            <%= cat_image.catname %>
        <% end %>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/create.js.erb
$('#bookmarks_buttons_<%= @cat_image.id %>').html("<%= j(render partial: 'cat_images/bookmark', locals: {cat_image: @cat_image}) %>");

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/destroy.js.erb
$('#bookmarks_buttons_<%= @cat_image.id %>').html("<%= j(render partial: 'cat_images/bookmark', locals: {cat_image: @cat_image}) %>");

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @cat_image.id %>').html("<%= j(render partial: 'cat_images/favorite', locals: {cat_image: @cat_image}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @cat_image.id %>').html("<%= j(render partial: 'cat_images/favorite', locals: {cat_image: @cat_image}) %>");

app/views/users/bookmark.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nekomamiretop</title>
</head>
<body>


  <div class="container-fluid">
      <div class="border" style="padding:20px; margin: 20px;">
        <h1 class="text-center">お気に入り一覧</h1>

        <div class="row">
              <div class="col-2"></div>

        <div class="col-8">

          <div class="table-responsive">
            <% @user.bookmark_cat_images.each do |cat_image| %>
              <table class="table table-bordered"  style="table-layout:fixed;">

                <tbody>
                  <td style="width:100px;">
                    <div class="text-center">
                      <%= link_to cat_image_path(cat_image.id) do %>
                        <%= attachment_image_tag cat_image, :image, :size =>'150x150' %>
                      <% end %>
                    </div>
                  </td>


                  <td style="width:200px;">
                    <ul>
                    <li><i class="fa fa-calendar fa-fw"></i><%= cat_image.created_at.strftime('%Y/%m/%d') %></li>
                    <li><i class="fa fa-user fa-fw"></i>

                  <% if cat_image.user.status == "退会済" %>
                    <%= "退会ユーザー" %>
                  <% else %>
                    <%= cat_image.user.name %>
                  <% end %>
                </li>

                <li>
                  <i class="fas fa-cat fa-fw"></i>catname:<%= cat_image.catname %></li>

                <li><i class="fas fa-paw fa-fw"></i>memo:<%= cat_image.memo %></li>


                <div> <i class="far fa-comment fa-fw"></i>
                  <%= link_to cat_image.comments.count, cat_image_path(cat_image.id) %>

<!-- いいね -->
                  <span id="favorites_buttons_<%= cat_image.id %>">
                     <%= render 'cat_images/favorite', cat_image: cat_image %>
                   </span>

<!-- お気に入り -->
                    <span id="bookmarks_buttons_<%= cat_image.id %>">
                  <%= render 'cat_images/bookmark', cat_image: cat_image %>
                </span>

<!-- tag -->
                <div>
                  <% cat_image.tag_list.each do |tag| %>
                    #<%= link_to tag,cat_images_path(tag_name: tag) %>
                  <% end %>
                </div>
              </ul>

              </td>
              </tbody>
            </table>
            <br>
        <% end %>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
      </div>
  </div>


</body>
</html>






app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="border" style="padding:50px; margin: 100px;">
  <h1 class="text-center">プロフィール編集</h1>
  <div class="row">
    <div class="col-3"></div>

    <div class="col-6">
    	<div class="table-responsive">
		<%= form_for(@user) do |f| %>


		 <table class="table table-bordered"  style="table-layout:fixed;">
              <tbody>
              	<div class="text-center">
  				<h4><i class="fa fa-user fa-fw"></i>
  				name</h4>
  					<%= f.text_field :name %>
  				<h4><i class="fa fa-user fa-fw"></i>address</h4>
  					<%= f.email_field :email %>
  					<%= f.submit '保存' %>
  				</div>

			  </tbody>
		</table>
		<% end %>
		</div>
	</div>
	<div class="col-3"></div>
  </div>
  </div>
</div>

app/views/users/leave.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nekomamire</title>
</head>
<body>


  <div class="container-fluid">
      <div class="border" style="padding:20px; margin: 20px 200px 20px 200px;">
        <h1 class="text-center">退会ページ</h1>
         	<div class="row">
            	<div class="col-2"></div>

        		<div class="col-8">

          			<div class="table-responsive">
            			<table class="text-center">
							<p>退会をすると投稿・お気に入り・コメント・いいねはできなくなります。</p>
							<p>退会をしても投稿画像はのこります。投稿名は「退会ユーザー」と表示されます。</p>
							<p>投稿を削除したい場合は、必ず退会前にご自身で削除をお願いします。</p>



 							<div class="text-center">
 							<%= link_to "退会する", withdrawl_user_path(@user.id), method: :patch, class:'btn btn-warning' %>
 						</div>
						</table>
					</div>
				</div>
				<div class="col-2"></div>
			</div>
	  </div>
  </div>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nekomamiretop</title>
</head>
<body>


  <div class="container-fluid">
      <div class="border" style="padding:20px; margin: 20px;">
        <% if @user.id == current_user.id %>
        <h1 class="text-center">まいぺ～じ</h1>
        <% else %>
        <h1 class="text-center"><%= @user.name %>さんの投稿一覧</h1>
        <% end %>


            <div class="row">
              <div class="col-3"> 
                <% if @user.id == current_user.id %>
                <div class="table-responsive">
                  <table class="table table-bordered"  style="table-layout:fixed;">
                     <td style="width:100px; padding: 50px">
                      <div class="text-center">

                      <%= "address: #{@user.email}" %><br>

                      <%= link_to "編集", edit_user_path(@user), class: 'btn btn-info btn-xs' %>
                      <%= link_to "退会する", leave_user_path(@user), class: 'btn btn-info btn-xs' %>
                      <%= link_to "お気に入り一覧", bookmark_user_path(@user), class: 'btn btn-info btn-xs' %>

                     </div>
                    </td>
                  </table>
                </div>
                <% end %>

              </div>

 <div class="col-7">

          <div class="table-responsive">

<% @cat_images.each do |cat_image| %>
<table class="table table-bordered"  style="table-layout:fixed;">
              <tbody>

              <td style="width:100px;">
                <div class="text-center">
    <%= link_to cat_image_path(cat_image.id) do %>
      <%= attachment_image_tag cat_image, :image, :size =>'150x150' %>
    <% end %>
</div>
</td>

<td style="width:200px; padding: 30px 20px 20px 30px">
                <ul>
                <li><i class="fa fa-calendar fa-fw"></i><%= cat_image.created_at.strftime('%Y/%m/%d') %></li>
                 <li>
                  <i class="fas fa-cat fa-fw"></i>catname:<%= cat_image.catname %></li>

                <li><i class="fas fa-paw fa-fw"></i>memo:<%= cat_image.memo %></li>


                <div> <i class="far fa-comment fa-fw"></i>
                  <%= link_to cat_image.comments.count, cat_image_path(cat_image.id) %>
<!-- いいね -->
                   <span id="favorites_buttons_<%= cat_image.id %>">
                     <%= render 'cat_images/favorite', cat_image: cat_image %>
                   </span>
<!-- お気に入り -->
                   <span id="bookmarks_buttons_<%= cat_image.id %>">
                  <%= render 'cat_images/bookmark', cat_image: cat_image %>
                </span>
<!-- tag -->
                <div>
                  <% cat_image.tag_list.each do |tag| %>
                    #<%= link_to tag,cat_images_path(tag_name: tag) %>
                  <% end %>
                </div>
              </ul>

              </td>
              </tbody>
            </table>
            <br>
        <% end %>
          </div>
        </div>
        <div class="col-2"></div>
</div>
</div>
</div>




</body>
</html>/