config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/create'
  get 'bookmarks/destroy'
   devise_for :admins, controllers: {sessions: 'admins/sessions'}

    devise_for :users
  resources :admin_users, only: [:index, :show, :edit, :update]
    get 'users/:id/mypage' => 'users#mypage', as: 'mypage_user'
  get 'users/leave' => 'users#leave'
  resources :users, only: [:edit, :update, :show]do

  member do
    get "leave"
    patch "withdrawl"
    get "bookmark"
  end
end

  get 'cat_images/all' => 'cat_images#all'
  get 'cat_images/rank' => 'cat_images#rank'
  resources :cat_images do
  	resource :favorites, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    end

  get 'homes/about'
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :cat_image
end

app/models/cat_image.rb
class CatImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :users, through: :bookmarks

	validates :image, presence: true
	validates :catname, presence: true
	validates :memo, presence: true




	acts_as_taggable

	def favorited_by?(user)
	 favorites.where(user_id: user.id).exists?
	end

	def bookmark_by?(user)
		bookmarks.where(user_id: user.id).exists?
	end
end

app/models/catimage.rb
class CatImage < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :cat_image

	validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :cat_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         # , :validatable

         validates :name, presence: true
         validates :email, presence: true
         # validates :password, presence: true


  has_many :cat_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_cat_images, through: :bookmarks, source: :cat_image

  enum status: {
  	会員: 0,
  	退会済: 1
  }





   def active_for_authentication?
  		super && (self.status === "会員")
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
  	@cat_image = CatImage.find(params[:cat_image_id])
  	bookmark = current_user.bookmarks.new(cat_image_id: @cat_image.id)
  	bookmark.save!
  end

  def destroy
  	@cat_image = CatImage.find(params[:cat_image_id])
  	bookmark = current_user.bookmarks.find_by(cat_image_id: @cat_image.id)
  	bookmark.destroy!
  end

  def show
  	@user = User.find(params[:user_id])
    @bookmarks = Bookmark.where("user_id = ?", @user)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
	cat_image = CatImage.find(params[:cat_image_id])
	message = current_user.comments.new(comment_params)
	message.cat_image_id = cat_image.id
	message.save
	redirect_to cat_image_path(cat_image)
	end

	def destroy
	Comment.find_by(id: params[:id], cat_image_id: params[:cat_image_id]).destroy
	redirect_to cat_image_path(params[:cat_image_id])
	end


	private
	def comment_params
		params.require(:comment).permit(:message)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :signed_in?, only: [:edit, :update]



  # def mypage
  #   user = current_user
  #   @cat_images = user.cat_images.all
  #   @user = User.find(params[:id])
  #   @cat_image = @user.cat_images.all
  #   @bookmarks = Bookmark.where("user_id = ?", @user)
  # end

  def show
    @user = User.find_by(id: params[:id])
    @cat_images = @user.cat_images
  end

  def edit
    @user = User.find(params[:id])
    if  @user == current_user
       render 'edit'
     else
      redirect_to cat_images_path
     end
  end

  def update
    @user = User.find(params[:id])
  if
    @user.update(user_params)
    redirect_to user_path(@user.id)
  else
    render 'edit'
  end
end

  def leave
    @user = User.find(params[:id])
  end

  def withdrawl
    @user = User.find(current_user.id)
    @user.update(status:"退会済")
    reset_session
    redirect_to root_path
  end

  def bookmark
    @user = User.find(params[:id])
    @bookmarks = Bookmark.where("user_id = ?", @user)
  end



  private
  def user_params
    params.require(:user).permit(:name, :email, :status, :id)
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/cat_images_helper.rb
module CatImagesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<script src="https://kit.fontawesome.com/7c6032e705.js" crossorigin="anonymous"></script>

<!DOCTYPE html>
<html>
  <head>
    <title>NekoMamire</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container-fluid">
          <div class="navbar-brand">
            <%= link_to image_tag('Free_Sample_By_Wix.jpg', :size => '80x80'),'/' %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-sample">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-around" id="navbarNav">
            <ul class="nav navbar-nav mr-auto">

              <% if user_signed_in? %>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "TOP", root_path %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to 'マイページ', user_path(current_user.id) %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "うちねこ", cat_images_path %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "ランキング", cat_images_rank_path %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>


              <% elsif admin_signed_in? %>
                <li>
                  <i class="far fa-check-square"></i><%= link_to "管理ログアウト",destroy_admin_session_path, method: :delete %>
                </li>
                <li>
                  <i class="far fa-check-square"></i><%= link_to "会員一覧",admin_users_path %>
                </li>

                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "TOP", root_path %>
                </li>

              <% else %>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "TOP", root_path %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "うちねこ", cat_images_path %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "ランキング", cat_images_rank_path %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "新規登録", new_user_registration_path %>
                </li>
                <li class="">
                  <i class="far fa-check-square"></i><%= link_to "ログイン", new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>




    <%= yield %>


    <footer>
      <div class="text-right">
      <p>©neko_mamire</p>
    </div>
    </footer>
  </body>
</html>