config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/create'
  get 'bookmarks/destroy'
   devise_for :admins, controllers: {sessions: 'admins/sessions'}

    devise_for :users
  resources :admin_users, only: [:index, :show, :edit, :update]
    get 'users/:id/mypage' => 'users#mypage', as: 'mypage_user'
  get 'users/leave' => 'users#leave'
  resources :users, only: [:edit, :update, :show]do

  member do
    get "leave"
    patch "withdrawl"
    get "bookmark"
  end
end

  get 'cat_images/all' => 'cat_images#all'
  get 'cat_images/rank' => 'cat_images#rank'
  resources :cat_images do
  	resource :favorites, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
    end

  get 'homes/about'
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :cat_image
end

app/models/cat_image.rb
class CatImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :users, through: :bookmarks

	validates :image, presence: true
	validates :catname, presence: true
	validates :memo, presence: true




	acts_as_taggable

	def favorited_by?(user)
	 favorites.where(user_id: user.id).exists?
	end

	def bookmark_by?(user)
		bookmarks.where(user_id: user.id).exists?
	end
end

app/models/catimage.rb
class CatImage < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :cat_image

	validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :cat_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         # , :validatable

         validates :name, presence: true
         validates :email, presence: true
         # validates :password, presence: true


  has_many :cat_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_cat_images, through: :bookmarks, source: :cat_image

  enum status: {
  	会員: 0,
  	退会済: 1
  }





   def active_for_authentication?
  		super && (self.status === "会員")
  end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
	 before_action :authenticate_admin!
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

   def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to admin_user_path(@user)
    end
private
    def user_params
    	params.require(:user).permit(:status, :member, :unmember)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
  	@cat_image = CatImage.find(params[:cat_image_id])
  	bookmark = current_user.bookmarks.new(cat_image_id: @cat_image.id)
  	bookmark.save!
  end

  def destroy
  	@cat_image = CatImage.find(params[:cat_image_id])
  	bookmark = current_user.bookmarks.find_by(cat_image_id: @cat_image.id)
  	bookmark.destroy!
  end

  def show
  	@user = User.find(params[:user_id])
    @bookmarks = Bookmark.where("user_id = ?", @user)
  end

end

app/controllers/cat_images_controller.rb
class CatImagesController < ApplicationController

before_action :authenticate_user!,except: [:index, :show, :all, :rank]


  def index
    @cat_images = CatImage.where(created_at: Time.now.all_month).page(params[:page]).reverse_order

    if params[:tag_name]
      @cat_images = CatImage.tagged_with("#{params[:tag_name]}").page(params[:page]).reverse_order
    end

    @tags = ActsAsTaggableOn::Tag.all

end

  def show
    @cat_image = CatImage.find(params[:id])
    @comment = Comment.new
  end

  def new
    @cat_image = CatImage.new
  end

  def create
    @cat_image = CatImage.new(cat_image_params)
    @cat_image.user_id = current_user.id
    if @cat_image.save
    redirect_to cat_images_path, notice:"投稿できたにゃ"
  else
    render 'new'
  end
  end

  def edit
    @cat_image = CatImage.find(params[:id])
  end

  def update
    cat_image = CatImage.find(params[:id])
    cat_image.update(cat_image_params)
      redirect_to cat_image_path(cat_image)

  end

  def destroy
    @cat_image = CatImage.find(params[:id])
    @cat_image.destroy
    redirect_to cat_images_path
  end

  def all
    @cat_images = CatImage.page(params[:page])
    @tags = ActsAsTaggableOn::Tag.all
  end

  def rank
    @all_ranks = CatImage.find(Favorite.group(:Cat_image_id).order('count(cat_image_id) desc').limit(10).pluck(:cat_image_id))
  end

  def bookmarks
    @cat_images = current_user.bookmark_cat_images.includes(:user).recent
  end

private
  def cat_image_params
    params.require(:cat_image).permit(:catname, :image, :memo, :tag_list)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
	cat_image = CatImage.find(params[:cat_image_id])
	message = current_user.comments.new(comment_params)
	message.cat_image_id = cat_image.id
	message.save
	redirect_to cat_image_path(cat_image)
	end

	def destroy
	Comment.find_by(id: params[:id], cat_image_id: params[:cat_image_id]).destroy
	redirect_to cat_image_path(params[:cat_image_id])
	end


	private
	def comment_params
		params.require(:comment).permit(:message)
	end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!

	def create
		@cat_image = CatImage.find(params[:cat_image_id])
		favorite = current_user.favorites.new(cat_image_id: @cat_image.id)
		favorite.save
	end

	def destroy
    	@cat_image = CatImage.find(params[:cat_image_id])
    	favorite = current_user.favorites.find_by(cat_image_id: @cat_image.id)
    	favorite.destroy
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :signed_in?, only: [:edit, :update]



  # def mypage
  #   user = current_user
  #   @cat_images = user.cat_images.all
  #   @user = User.find(params[:id])
  #   @cat_image = @user.cat_images.all
  #   @bookmarks = Bookmark.where("user_id = ?", @user)
  # end

  def show
    @user = User.find_by(id: params[:id])
    @cat_images = @user.cat_images
  end

  def edit
    @user = User.find(params[:id])
    if  @user == current_user
       render 'edit'
     else
      redirect_to cat_images_path
     end
  end

  def update
    @user = User.find(params[:id])
  if
    @user.update(user_params)
    redirect_to user_path(@user.id)
  else
    render 'edit'
  end
end

  def leave
    @user = User.find(params[:id])
  end

  def withdrawl
    @user = User.find(current_user.id)
    @user.update(status:"退会済")
    reset_session
    redirect_to root_path
  end

  def bookmark
    @user = User.find(params[:id])
    @bookmarks = Bookmark.where("user_id = ?", @user)
  end



  private
  def user_params
    params.require(:user).permit(:name, :email, :status, :id)
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/cat_images_helper.rb
module CatImagesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_images/_bookmark.html.erb
<% if cat_image.bookmark_by?(current_user) %>
                      <%= link_to cat_image_bookmarks_path(cat_image), method: :delete, remote: true do %>
                      <i class="fas fa-bookmark fa-fw"></i>
                        <%= "#{cat_image.bookmarks.count}" %>
                      <% end %>
                    <% else %>
                      <%= link_to cat_image_bookmarks_path(cat_image), method: :post, remote: true do %>
                      <i class="far fa-bookmark fa-fw"></i>
                        <%= "#{cat_image.bookmarks.count}" %>
                      <% end %>
                    <% end %>

app/views/cat_images/_favorite.html.erb
<% if cat_image.favorited_by?(current_user) %>
                      <%= link_to cat_image_favorites_path(cat_image), method: :delete, remote: true do %>
                        <i class="fas fa-heart fa-fw"></i>
                          <%= "#{cat_image.favorites.count}" %>
                      <% end %>
                    <% else %>
                      <%= link_to cat_image_favorites_path(cat_image), method: :post, remote: true do %>
                          <i class="far fa-heart fa-fw" aria-hidden="true"></i>
                            <%= "#{cat_image.favorites.count}" %>
                      <% end %>
                    <% end %>

app/views/cat_images/_list.html.erb
<div class="table-responsive">
            <% cat_images.each do |cat_image| %>
            <table class="table table-bordered"  style="table-layout:fixed;">
              <tbody>

              <td style="width:100px; padding: 30px 20px 20px 30px">
                <div class="center">
                  <%= link_to cat_image_path(cat_image.id) do %>
                  <%= attachment_image_tag cat_image, :image, :size =>'150x150' %>
                <% end %>
              </div>
              </td>


              <td style="width:200px; padding: 30px 20px 20px 30px">
                <div class="v-align-middle">
                <ul>
                <li><i class="fa fa-calendar fa-fw"></i><%= cat_image.created_at.strftime('%Y/%m/%d') %></li>
                <li><i class="fa fa-user fa-fw"></i>

                  <% if cat_image.user.status == "退会済" %>
                    <%= "退会ユーザー" %>
                  <% else %>
                    <%= link_to "#{cat_image.user.name}", user_path(cat_image.user_id) %>
                  <% end %>
                </li>

                <li>
                  <i class="fas fa-cat fa-fw"></i>catname:<%= cat_image.catname %></li>

                <li><i class="fas fa-paw fa-fw"></i>memo:<%= cat_image.memo %></li>


                <div> <i class="far fa-comment fa-fw"></i>
                  <%= link_to cat_image.comments.count, cat_image_path(cat_image.id) %>
<!-- いいね -->
                  <% if signed_in? %>
                     <span id="favorites_buttons_<%= cat_image.id %>">
                     <%= render 'cat_images/favorite', cat_image: cat_image %>
                   </span>
                  <% else %>
                    <i class="far fa-heart fa-fw"></i>
                      <%= "#{cat_image.favorites.count}" %>
                  <% end %>
<!-- お気に入り -->
                  <% if signed_in? %>
                  <span id="bookmarks_buttons_<%= cat_image.id %>">
                  <%= render 'cat_images/bookmark', cat_image: cat_image %>
                </span>
                    <% else %>
                    <i class="far fa-bookmark fa-fw"></i>
                        <%= "#{cat_image.bookmarks.count}" %>
                    <% end %>


                </div>
<!-- tag -->
                <div>
                  <% cat_image.tag_list.each do |tag| %>
                    #<%= link_to tag,cat_images_path(tag_name: tag) %>
                  <% end %>
                </div>
              </ul>
            </div>
              </td>
              </tbody>
            </table>
            <br>
        <% end %>
          </div>

app/views/cat_images/all.html.erb
<div class="container-fluid">
  <div class="border" style="padding:20px; margin: 20px;">
  <h1 class="text-center">お～るうちねこみてください</h1>
    <div class="border" style="padding:10px;">
            <p class="text-center">
            ここでは今まで投稿された全部のうちねこをみることができます。<br>
            お気に入りを増やしたり気になるタグをクリックで同じタグのついた猫画像を探せます。
            </p>
    </div>


  <div class="row" style="padding:20px">
    <div class="col-2">
                <% @tags.each do |tag| %>
                <%= link_to "#{tag.name}(#{tag.taggings_count})", cat_images_path(tag_name: tag.name), class: "label label-default" %> 
                <% end %>
    </div>

    <div class="col-8">
     <%= render 'cat_images/list', cat_images: @cat_images %>
   </div>
    <div class="col-2"></div>
  </div>
</div>
<%= paginate @cat_images %>

app/views/cat_images/edit.html.erb
<!DOCTYPE html>
<html>

  <body>

    <div class="container-fluid">

        <h3 class="text-center">うちねこへんしゅ～</h3>

          <div class="row">
            <div class="col-4"></div>

            <div class="col-4">

            <div class="row flex-column align-items-center">
              <div class="col-6">
                  <%= attachment_image_tag @cat_image, :image, :size => '150x150' %>
              </div>

              	<%= form_for(@cat_image) do |f| %>
              <div class="col-6">
                      <ul>
                        <li>catname:
                      <%= f.text_field :catname %></li><br>

                      <li>memo:
                      <%= f.text_area :memo %></li><br>
                      <li>tag:
                      <%= f.text_field :tag_list, value: @cat_image.tag_list.join(',') %></li><br>

                    <li><%= f.submit "保存", class:"btn btn-primary btn-block btn-xs" %></li><br>
                    </ul>

              </div>
            </div>

            <% end %>
            <div class="col-4"></div>

          </div>
    </div>
  </body>

</html

app/views/cat_images/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nekomamiretop</title>
</head>
<body>


  <div class="container-fluid">
      <div class="border" style="padding:20px; margin: 20px;">
        <h1 class="text-center">今月のうちねこみてください</h1>
        <div class="border" style="padding:10px;">
            <p class="text-center">

            ここではネコちゃんの見てコレ！な瞬間の画像を見ることができます。<br>
            あなたの周りのネコちゃんのかわいい・おもしろい・びっくりな瞬間の画像をお待ちしております。<br>
            お気に入りのネコちゃんを見つけたらぜひイイネやコメント、お気に入り登録を。<br>
            お気に入りのネコちゃんをツイッターでみんなに教えてあげましょう☆<br>
            毎月1日にリセットされます。今までの投稿は下のallから見ることができます。
            </p>
          </div>


          <div class="text-right">
            +<%= link_to new_cat_image_path do %>
            <i class="fas fa-cat fa-fw fa-4x"></i>
            <% end %>
            all<%= link_to cat_images_all_path do %>
            <i class="fas fa-cat fa-fw fa-4x"></i>
            <% end %>
          </div>


            <div class="row">
              <div class="col-2">
                <% @tags.each do |tag| %>
                <%= link_to "#{tag.name}(#{tag.taggings_count})", cat_images_path(tag_name: tag.name), class: "label label-default" %>
                <% end %>

              </div>

        <div class="col-8">

        <%= render 'cat_images/list', cat_images: @cat_images %>
      </div>
        <div class="col-2"></div>
</div>
</div>
</div>

<%= paginate @cat_images %>
</body>
</html>

app/views/cat_images/new.html.erb
<!DOCTYPE html>
<html>

  <body>

    <div class="container-fluid">

        <h3 class="text-center">うちねこと～こ～</h3>

          <div class="row">
            <div class="col-2"></div>

            <div class="col-8">

          <div class="d-flex flex-column align-items-center">
            <%= form_for(@cat_image) do |f| %>

              <div class="col">

                <% if @cat_image.errors.any? %>
                  <ul><li><%= @cat_image.errors.count %>件のエラーが発生しました<br></li>
                    <% @cat_image.errors.full_messages.each do |message| %>
                      <li><%= message %></li>

                    <% end %>
                  </ul>
                <% end %>
                <%= attachment_image_tag @cat_image, :image, :fill, 300, 300, format: 'jpeg' %>
                  <%= f.attachment_field :image, placeholder: "猫ちゃん" %>
                  <p>正方形サイズがおすすめです</p>
              </div>

              <div class="col">
                <ul>
                  <li>catname:
                      <%= f.text_field :catname %></li><br>

                  <li>memo:
                      <%= f.text_area :memo %></li><br>

                  <li>tag:
                      <%= f.text_area :tag_list, value: @cat_image.tag_list.join(',') ,class: "form-control",placeholder: "タグ,タグ..." %></li><br>
                  <li>
                      <%= f.submit "新規登録", class:"btn btn-primary btn-block" %></li></ul>
              </div>
              <% end %>
          </div>

            </div>
            <div class="col-2"></div>
          </div>
    </div>

  </body>

</html>

app/views/cat_images/rank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nekomamiretop</title>
</head>
<body>


  <div class="container-fluid">
      <div class="border" style="padding:20px; margin: 20px;">
        <h1 class="text-center">うちねこいいねらんく</h1>

          <div class="border" style="padding:10px;">
            <p class="text-center"> ここは投稿されたうちネコ画像のいいねランキングです。
          上位１０位まで随時更新されていきます。<br>
          投稿したネコちゃんがランキング入りしているかぜひチェックしてみてください☆
            </p>
          </div>


          <div class="row">
            <div class="col-2"></div>

              <div class="col-8">

                <div class="table-responsive">
                  <% @all_ranks.each_with_index do |cat_image, i| %>

                   <table class="table table-bordered"  style="table-layout:fixed;">
                    <tbody>
                      <i class="fas fa-crown"></i>
                      <%= i+1 %>位
                      <td style="width:100px; padding: 30px 20px 20px 30px">
                        <div class="text-center"><%= link_to cat_image_path(cat_image.id) do %>
  		                    <%= attachment_image_tag cat_image, :image, :size =>'150x150' %>
  	                       <% end %>
                            </div>
                             </td>

                              <td style="width:200px; padding: 30px 20px 20px 30px">
                          <ul>
                          <li><i class="fa fa-calendar fa-fw"></i><%= cat_image.created_at.strftime('%Y/%m/%d') %></li>
                          <li><i class="fa fa-user fa-fw"></i>

                            <% if cat_image.user.status == "退会済" %>
                              <%= "退会ユーザー" %>
                            <% else %>
                              <%= cat_image.user.name %>
                            <% end %>
                          </li>

                          <li>
                            <i class="fas fa-cat fa-fw"></i>catname:<%= cat_image.catname %></li>

                          <li><i class="fas fa-paw fa-fw"></i>memo:<%= cat_image.memo %></li>
          <!-- いいね -->
                          <div> <i class="far fa-comment fa-fw"></i>
                            <%= link_to cat_image.comments.count, cat_image_path(cat_image.id) %>

                             <% if signed_in? %>
                                <span id="favorites_buttons_<%= cat_image.id %>">
                                <%= render 'cat_images/favorite', cat_image: cat_image %>
                                </span>
                             <% else %>
                              <i class="far fa-heart fa-fw"></i>
                                <%= "#{cat_image.favorites.count}" %>
                            <% end %>
          <!-- お気に入り -->
                             <% if signed_in? %>
                              <span id="bookmarks_buttons_<%= cat_image.id %>">
                                <%= render 'cat_images/bookmark', cat_image: cat_image %>
                              </span>
                             <% else %>
                              <i class="far fa-bookmark fa-fw"></i>
                                  <%= "#{cat_image.bookmarks.count}" %>
                             <% end %>
                          </div>
          <!-- tag -->
                          <div>
                            <% cat_image.tag_list.each do |tag| %>
                              #<%= link_to tag,cat_images_path(tag_name: tag) %>
                            <% end %>
                          </div>
                        </ul>

              </td>
              </tbody>
            </table>
            <br>
        <% end %>
          </div>
        </div>
        <div class="col-2"></div>
</div>
</div>
</div>


</body>
</html>

app/views/cat_images/show.html.erb
<script src="https://kit.fontawesome.com/7c6032e705.js" crossorigin="anonymous"></script>

    <div class="container-fluid">
      <div class="border" style="padding:10px;">
       <h1 class="text-center">しょ～さい</h1>

            <div class="d-flex justify-content-center">

              <div class="d-flex flex-row bd-highlight mb-3">

                <div class="p-2 bd-highlight"> <%= attachment_image_tag @cat_image, :image, :size =>'300x300' %></div>

                  <div class="p-2 bd-highlight"></div>
                  <div class="p-2 bd-highlight"></div>

                  <div class="align-self-center">

                    <ul>
                      <li>
                      <i class="fa fa-user fa-fw"></i>
                      <%= "By" %>
                        <% if @cat_image.user.status == "退会済" %>
                          <%= "退会ユーザー" %>
                        <% else %>
                          <%= link_to "#{@cat_image.user.name}", user_path(@cat_image.user_id) %>
                        <% end %>
                      </li>

                      <li>
                        <i class="fas fa-cat fa-fw"></i>
                        <%= "catname ： #{@cat_image.catname}" %>
                      </li>

                      <li>
                    <i class="fas fa-paw fa-fw"></i>
                    <%= "memo　:　#{@cat_image.memo}" %>
                  </li>

                  <li>
                    <i class="fa fa-calendar fa-fw"></i>
                    <%= "#{@cat_image.created_at.strftime('%Y/%m/%d')}" %>
                    </li>


        <!-- いいね関係 --><li>
                  <% if signed_in? %>
                        <span id="favorites_buttons_<%= @cat_image.id %>">
                     <%= render 'cat_images/favorite', cat_image: @cat_image %>
                   </span>
                  <% else %>
                    <i class="far fa-heart fa-fw"></i>
                      <%= "#{@cat_image.favorites.count}" %>
                  <% end %>

                          <li>
                            <i class="fa fa-comment fa-fw"></i>
                              <%= "#{@cat_image.comments.count}" %>
                              <%= "件" %>
                          </li>

                          <li>
                  <% if signed_in? %>
                            <span id="bookmarks_buttons_<%= @cat_image.id %>">
                  <%= render 'cat_images/bookmark', cat_image: @cat_image %>
                </span>
                  <% else %>
                    <i class="far fa-bookmark fa-fw"></i>
                      <%= "#{@cat_image.bookmarks.count}" %>
                  <% end %>
                          </li>

                          <li>
                            <% @cat_image.tag_list.each do |tag| %>
                              #<%= link_to tag,cat_images_path(tag_name: tag) %>
                            <% end %>
                          </li>
                          <li></li>

                          <li>
                          <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="お気に入りのネコちゃんです。" data-hashtags="#うちねこ見て" data-lang="ja" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                        </li>
                      </ul>
                    </div>

                      <div class="align-self-end">
                       <% if @cat_image.user == current_user %>
                          <ul>
                          <li><%= link_to "編集", edit_cat_image_path(@cat_image) %>｜
                            <%= link_to "削除", cat_image_path(@cat_image), method: :delete, data: { confirm: '本当に削除しますか？' } %>
                        <% end %>
                          </li>
                        </ul>

                        </div>



              </div>
            </div>
          </div>


<!-- コメント -->

    <%= form_for [@cat_image, @comment] do |f| %>
      <div class="row">
        <div class="col-sm-12">
          <%= f.text_area :message, rows:'5', class: "form-control",placeholder: "コメントを入力してください" %>
        </div>
      </div>
        <%= f.submit "送信する", class: "btn btn-outline-secondary btn-sm" %>
    <% end %>

    <% @cat_image.comments.each do |comment| %>
      <i class="fal fa-comments"></i>
        <%= comment.created_at.strftime('%Y/%m/%d') %> 
        <%= comment.user.name %>さん
        <%= comment.message %>
      <% if comment.user == current_user %>
        <div>
          <%= link_to "削除", cat_image_comment_path(comment.cat_image, comment), method: :delete, data: { confirm: 'コメントを削除しますか？' },class: "btn btn-outline-danger btn-sm" %>
        </div>
      <% end %>
      <br>
    <% end %>





        </div>
      </div>
    </div>